server:
  port: 8100
spring:
  application:
    name: service-verification-code
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.3:8888
        username: nacos
        password: nacos