server:
  port: 8097
spring:
  application:
    name: service-passenger-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.3:8888
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: Gepoint