server:
  port: 8093
spring:
  application:
    name: jerry-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8099
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: Gepoint